/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Document {
  'id' : bigint,
  'createdAt' : bigint,
  'personId' : bigint,
  'blobId' : string,
  'docType' : string,
}
export interface Person { 'id' : bigint, 'name' : string }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addDocument' : ActorMethod<[bigint, string, string], bigint>,
  'addPerson' : ActorMethod<[string], bigint>,
  'deleteAllDocuments' : ActorMethod<[], undefined>,
  'deleteDocument' : ActorMethod<[bigint], undefined>,
  'deletePerson' : ActorMethod<[bigint], undefined>,
  'getAllDocuments' : ActorMethod<[], Array<Document>>,
  'getAllPersons' : ActorMethod<[], Array<Person>>,
  'getDocument' : ActorMethod<[bigint], [] | [Document]>,
  'getDocumentsForPerson' : ActorMethod<[bigint], Array<Document>>,
  'getPerson' : ActorMethod<[bigint], [] | [Person]>,
  'searchPersons' : ActorMethod<[string], Array<Person>>,
  'updateDocumentBlob' : ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];